# Generated by Django 2.1 on 2018-10-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facultylogin', '0003_aptitude_cse_ece_eee_gk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APTITUDE',
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='GK',
        ),
    ]
